export const aboutText = `
## How To Use This Site

Welcome! I invite you to explore this site and its comparisons of excerpts from _Outlaws of the Marsh_ and _The Merry Adventures of Robin Hood._ Both novels are very well-known and have remained popular through the test of time, and they noticeably share many similarities. By comparing various sections from the texts, the similarities are apparent, but the differences in Western and Chinese culture, particularly surrounding masculinity, are revealed.

The novels share the concept of _xia_ (侠), or knight-errant. The term knight-errant refers to a wandering knight who travels in search of adventure, much like the _youxia_ (游侠), who is a travelling warrior fighting for those who can’t defend themselves. _Outlaws of the Marsh_ includes the stories of multiple characters who travel and undertake adventures on their path to becoming the bandits at Liangshan. _The Merry Adventures of Robin Hood_ is structured in a very similar manner, but following the adventures of Robin Hood as he becomes a heroic outlaw, who steals from the rich and gives to the poor, instead of more than one protagonist.

To begin, the home page allows you to toggle between stories from _The Merry Adventures of Robin Hood_ and _Outlaws of the Marsh_. Each of the stories has a counterpart from the other novel, and clicking any of them will take you to a page dedicated to that excerpt. On that page, both the original excerpt and an amalgamation of lines from both novels that tell the matching excerpt. Toggling between views of the two novels will show the sister excerpt and its re-written counterpart as well.

This format aims to highlight the broad similarities in these novels, which makes it possible to rewrite each excerpt using text from the other novel. It also brings out differences in characterization and tone, which point to specific differences in Western and Chinese conceptions about masculinity.

As a fun tidbit, you can see which character from _Outlaws of the Marsh_ or _The Merry Adventures of Robin Hood_ you are most like by taking a short quiz on the [quiz](/quiz) tab!

## Chinese Masculinity: _wen_ and _wu_

Western work on masculinity has described the Occidental male as defining his notion of the male self in terms of images of toughness, courage, and decisiveness. Western heroes tend to have an adventurous spirit and proclivity to violence, tending towards physical rather than oral expressions of their feelings. However, this type of macho masculinity is not the typical Chinese male’s self image of masculinity. While these adventurous types of masculine heroes exist, like the _yingxiong_ (英雄) or _haohan_ (好汉), they are counterbalanced by a softer scholarly tradition, which dominates the model of Chinese masculinity.

A better paradigm to analyze Chinese masculinity with would be the binary opposition between _wen_ (文), the cultural and civil, and _wu_ (武), the physical or martial. The two masculine archetypes of _wen_ and _wu_ are the scholar and soldier respectively. Chinese masculinity actually comprises both, and the scholar is in fact no less masculine than the soldier. There have been shifts in the ideals of masculinity and masculine beauty over the dynasties. For example, men during the Tang period cultivated a martial appearance, with thick beards, and admired bodily strength, with civilian and military officials practicing sword fighting and riding. But under Manchu occupation, martial strength became associated with the conquerors, and within the Chinese literary class the ideal lover became one who has a quiet scholarly demeanor.

_Wen_ and _wu_ refer specifically to the ancient Kings of the Zhou: King Wen and King Wu. The Book of Rites describes their differences in ruling style, saying that King Wen used culture to rule and King Wu used military power. While the two form a dichotomy, they were not in competition. It is beneficial to possess qualities of both _wen_ and _wu_; many emperors strove to show their subjects that they did in fact have both.


## Notes From the Creator

From the start, Robin Hood and Major Lu Da have a lot of similarities in plot. [“Major Lu Pummels the Lord of the West”](/story/1?perspective=outlaw) and [“Robin Hood Becomes an Outlaw”](/story/1?perspective=robinhood) are chapters that tell the story of how these two characters became outlawed and began their adventures. Both become outlaws unintentionally, one killing the tormentor of a girl and her father, and the other shooting a man who’d shot at him first. Switching their narratives was very natural because they were so similar, but it stands out that the Eastern and Western characterizations differ greatly. Robin Hood is portrayed more as a young and innocent lad who makes a mistake, while Lu Da is much more violent and vulgar in his language. However, I’d contend that Robin Hood killed someone in a fit of anger, but Lu Da was actually saving someone else and couldn’t control his strength. These differences in characterization point at the differences in Chinese and Western conceptions of masculinity, where Lu Da is the macho brawny Chinese male, which is not common but is the de facto image of Western masculinity. Lu Da exhibits some wu characteristics but no wen traits, which is also true of Robin Hood and his adventures, but Robin is depicted as courageous and adventurous while Lu Da is an unmannered brute who has great strength.

Robin Hood and Lu Da also both build a band of loyal followers. [“Tattooed Monk and His Band”](/story/2?perspective=outlaw) and [“Robin Hood’s Feast”](/story/2?perspective=robinhood) illustrate the bond and how happy these groups of men are around each other. This was the easiest narrative swap, and was almost one-to-one because Robin and Sagacious are each respected and accepted by their men. A stylistic difference is that Robin Hood’s feast seems much more lively and rambunctious, while that of Sagacious’ feast contains less detail about the interactions and instead lists the food and drink being served.

An interesting contrast is that of [“Sagacious Lu Puts Mount Wutai in an Uproar”](/story/4?perspective=outlaw) and [“Robin Hood Seeks the Curtal Friar”](/story/4?perspective=robinhood), where Sagacious and Friar Tuck are both religious men, eating, but Friar Tuck’s behavior is comedic and Sagacious’ is extremely offensive. Friar Tuck is being observed by Robin Hood, while Sagacious is interacting with other monks. Later, Sagacious also finds his community in a band of outlaws, feasting jovially with them as discussed above. Neither character can be accepted into religious society, Buddhist or Christian, but are able to bond with other men who do not follow religious rules. However, their depictions also differ because Chinese masculinity has the concept of both wen and wu, where discipline and being well-mannered is valued. On the other hand, Western culture which prioritizes a more brawny masculinity frequently depicts violent brawls, heavy drinking, and messy feasting. Stereotypically, medieval knights feasting in a castle hall will have an endless supply of ale and eat bountiful amounts of meat, paying no attention to the grease or mess. On the other hand, in Chinese works there are frequently very elegant and dignified banquets, like the Heavenly Peach Banquet was intended in Journey to the West before it was disrupted by Monkey.

Finally, in [“Song Jiang Secretly Helps Ward Chief Chao Flee”](/story/3?perspective=outlaw), Song Jiang aids Chao Gai with great risk to himself, showing his loyalty to his friend. In fact, Chao Gai has many friends including Zhu Tong and Lei Heng, who help him escape even though he has been caught doing something criminal. Similarly, in [“Will Stutely Rescued by his Companions”](/story/3?perspective=robinhood), the group refuses to leave anyone behind, and is willing to die for each other if needed. In both Chinese and Western cultures, loyalty is seen as a masculine ideal, and men are praised for their brotherhood and loyalty to each other. It is particularly interesting that Will Stutely hides his tears on the way to the gallows “lest the folk should think him unmanly,” but is able to openly weep with his comrade Little John when he is saved. Toxic masculinity belittles men who show emotion openly, but it is beautiful that Will Stutely and Little John are able to be vulnerable with each other without feeling emasculated.

While _Outlaws of the Marsh_ and _The Merry Adventures of Robin Hood_ share many similarities in their characters and plots, the nuanced differences illuminate the differences between Chinese and Western culture, specifically how masculinity is viewed. Through exchanging their language and descriptors for various stories, it became apparent that cultural attitudes on certain themes, such as violence and brawn, are very different, while other features of masculinity are shared, like loyalty and brotherhood.

The ideals of knight errantry were justice, altruism, honour, and individual freedom. This is much more similar to Western masculinity’s demand for an affinity for adventure and a craving for danger. In many ways, the knight errant formed a strong contrast to the Confucian scholar. While the Confucian scholar aimed at order and moderation, and stressed the need for the individual to conform to a rigid pattern of behaviour and to prioritize the family, the knight errant stressed justice and freedom and placed personal loyalty above family loyalty and above law and order.

The knight errant way of thinking has been said to be similar to Taoism. Some knights errant turned to Taoism for guidance, as both emphasized individualism and freedom from social bonds. Stereotypically, the West is familiar with the side of the Chinese character that is moderate, rigid, and conservative, but the knight errant is not a part of that, and is more romantic, individualist, and rebellious. As such, the depictions of the knight errant figure in _Outlaws of the Marsh_ are sometimes straight up brutish, because they do not conform to Confucian standards. By understanding _wen_ and _wu_ and perhaps even evaluating Western characters using this dichotomy, we can see how the protagonist knight errant figures of these two works are portrayed in context of their different cultures. The more heroic light that Robin Hood is portrayed in reflects that the knight errant’s characteristics are more closely aligned with the image of Western masculinity.
`